name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build the Docker image
      run: docker compose -f docker-compose.m1.yml up --build -d
    - name: Wait for server to be ready
      run: sleep 10
    - name: Run tests
      run: npm run test
    - name: Stop and remove containers
      run: docker compose -f file.yml down
